export const REQUEST_EMP_DATA = "REQUEST_EMP_DATA";
export const RECEIVE_EMP_DATA = "RECEIVE_EMP_DATA";
export const REQUEST_EMP_ADDR_DATA = "REQUEST_EMP_ADDR_DATA";
export const RECEIVE_EMP_ADDR_DATA = "RECEIVE_EMP_ADDR_DATA";
